### ISSUE TITLE
Move code.py functionality into lib?

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-lib#69]
It's quite big now and is probably taking a while to load.

**Comment by NovusEdge** [comment]
Hey!

I'd like to take this issue up if it's still open and available.

**Comment by mechawrench** [comment]
Hi, thank you for your interest in the project.

A requirement for contributing here is to have a fully functional (all features) WiFiCom device so that you can test while coding.  We will test near the end but you must ensure it’s working on your device before you PR.

I’d advise starting on a smaller task, this one is a substantial change to the project and something the maintainers are going to take on.

Thanks again for your willingness to help
